# Generated by Django 2.2.6 on 2019-10-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='required_time',
            field=models.DurationField(),
        ),
    ]
