# Generated by Django 2.2.6 on 2019-10-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191028_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='types',
            new_name='meal_type',
        ),
    ]
