# Generated by Django 2.2.6 on 2019-10-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191028_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disliked_recipes',
        ),
        migrations.AddField(
            model_name='profile',
            name='disliked_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_recipes', to='api.Recipe'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_recipes',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_recipes', to='api.Recipe'),
        ),
    ]
