# Generated by Django 2.2.6 on 2019-10-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191028_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.ManyToManyField(related_name='recipe', to='api.MealType'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_time',
            field=models.ManyToManyField(related_name='recipe', to='api.MealTime'),
        ),
    ]
