# Generated by Django 2.2.6 on 2019-10-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191031_0807'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='recipe',
        #     name='time',
        # ),
        # migrations.AddField(
        #     model_name='recipe',
        #     name='total_time',
        #     field=models.PositiveIntegerField(default=0),
        # ),
    ]
