# Generated by Django 2.2.6 on 2019-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, choices=[('Protein', 'Protein'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Dairy', 'Dairy'), ('Grain', 'Grain'), ('Bean', 'Bean'), ('Nut', 'Nut')], max_length=20, null=True),
        ),
    ]
