# Generated by Django 2.2.6 on 2019-10-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191028_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealType',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='MealTime',
            new_name='Meal',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='required_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.AddField(
            model_name='recipe',
            name='course',
            field=models.ManyToManyField(related_name='recipes', to='api.Course'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.ManyToManyField(related_name='recipes', to='api.Meal'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='api.Cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='api.Ingredient'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('required_time', models.DurationField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.Recipe')),
            ],
        ),
    ]
