# Generated by Django 2.2.6 on 2019-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191029_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(blank=True, default=0),
        ),
    ]
