# Generated by Django 2.2.6 on 2019-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191029_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disliked_recipes',
            field=models.ManyToManyField(blank=True, related_name='disliked_recipes', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes', to='api.Recipe'),
        ),
    ]
