# Generated by Django 2.2.6 on 2019-10-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recipe_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disliked_recipes',
            field=models.ManyToManyField(blank=True, related_name='disliked_recipes', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
