# Generated by Django 2.2.6 on 2019-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191105_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, choices=[('Protein', 'Protein'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Dairy', 'Dairy'), ('Grain', 'Grain'), ('Bean', 'Bean'), ('Nut', 'Nut'), ('Others', 'Others')], max_length=20, null=True),
        ),
        # migrations.AlterField(
        #     model_name='recipe',
        #     name='total_time',
        #     field=models.DurationField(blank=True, default='00:00:00', null=True),
        # ),
    ]
