# Generated by Django 2.2.6 on 2019-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_recipe_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
