# Generated by Django 2.2.6 on 2019-10-30 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
