# Generated by Django 2.2.6 on 2019-10-30 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191030_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(default=datetime.datetime(2019, 10, 30, 7, 38, 52, 119679, tzinfo=utc)),
        ),
    ]
