# Generated by Django 2.2.6 on 2019-11-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191110_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='meal',
            new_name='meals',
        ),
    ]
